export const insights = [
  {
    name: "Tomato Early Blight",
    designation: "Fungal Pathogen",
    src: "https://utfs.io/f/xnWEjJrtEUj0YZrH0pIcRbPaCwkXuWIxNS6U5tD2ys8grh1M",
    quote:
      "Sistem mendeteksi indikasi Bercak Daun Kering. Jamur Alternaria solani ini menyebar melalui air dan angin. Segera pangkas bagian terinfeksi dan aplikasikan fungisida tembaga untuk isolasi sektor.",
    extraBadge: "99.9% Match",
  },
  {
    name: "Mango Gall Midge",
    designation: "Insect Infestation",
    src: "https://pm4hcnxzio.ufs.sh/f/xnWEjJrtEUj0dDUeudnWUfXlSVc45CGmit2apDs709ZeWjBg",
    quote:
      "Terdeteksi serangan larva Procontarinia matteiana yang membentuk bintil pada daun. Segera pangkas tunas yang terinfeksi parah dan gunakan insektisida sistemik saat pucuk muda mulai muncul.",
    extraBadge: "81.8% Match",
  },
  {
    name: "Potato Pest Damage",
    designation: "Ecological Stress",
    src: "https://pm4hcnxzio.ufs.sh/f/xnWEjJrtEUj0rpHMKavAXs47vwpqu8oBaz5feUCkgiyPLObt",
    quote:
      "Indikasi kerusakan akibat hama (kutu daun/ulat). Lakukan rotasi tanaman non-solanaceae dan gunakan insektisida organik minyak mimba. Segera bersihkan gulma yang menjadi tempat persembunyian hama.",
    extraBadge: "99.5% Match",
  },
  {
    name: "Corn Leaf Blight",
    designation: "Fungal Infection",
    src: "https://pm4hcnxzio.ufs.sh/f/xnWEjJrtEUj0e2kfyYEAwbqO9LhZXI7zam2SdT50ElUnx1CP",
    quote:
      "Terdeteksi bercak cokelat memanjang akibat jamur Exserohilum turcicum. Pastikan sirkulasi udara optimal dan aplikasikan fungisida berbahan aktif mankozeb untuk mencegah gangguan fotosintesis massal.",
    extraBadge: "99.8% Match",
  },
];

export const mockLands = [
  {
    id: "land-1",
    name: "Blok Mangrove Utama - Muara Angke",
    position: [-6.111, 106.772] as [number, number],
    area_ha: 15.5,
    health_status: "NORMAL",
    address: "Pesisir Utara Sektor A",
    health_reports: [
      {
        id: "r1",
        confidence_score: 0.98,
        gemini_insight: {
          causes: "Optimasi Nutrisi Salinitas",
          recovery: "Sangat Baik",
          prevention: ["Monitoring berkala"],
          treatment: ["Lanjutkan pembersihan sampah plastik"],
          disease_description: "Vegetasi Mangrove Sangat Sehat",
        },
        is_outbreak_trigger: false,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "land-2",
    name: "Konservasi Elang Laut",
    position: [-6.115, 106.745] as [number, number],
    area_ha: 12.2,
    health_status: "WARNING",
    address: "Suaka Margasatwa Muara Angke",
    health_reports: [
      {
        id: "r2",
        confidence_score: 0.92,
        gemini_insight: {
          causes: "Pencemaran Limbah Cair",
          recovery: "Proses Pemulihan",
          prevention: ["Filter sedimentasi"],
          treatment: ["Netralisasi pH air"],
          disease_description: "Klorosis pada daun bibit muda",
        },
        is_outbreak_trigger: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "land-3",
    name: "Hutan Kota Penjaringan",
    position: [-6.125, 106.785] as [number, number],
    area_ha: 8.4,
    health_status: "NORMAL",
    address: "Jakarta Utara",
    health_reports: [],
  },
  {
    id: "land-4",
    name: "Lahan Pertanian Terpadu Rorotan",
    position: [-6.155, 106.945] as [number, number],
    area_ha: 45.0,
    health_status: "DANGER",
    address: "Sentra Padi Cilincing",
    health_reports: [
      {
        id: "r4",
        confidence_score: 0.99,
        gemini_insight: {
          causes: "Wereng Cokelat",
          recovery: "Kritis",
          prevention: ["Rotasi Tanaman"],
          treatment: ["Penyemprotan insektisida sistemik massal"],
          disease_description: "Outbreak hama wereng pada 5 hektar utama",
        },
        is_outbreak_trigger: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "land-5",
    name: "Mangrove Kapuk Muara",
    position: [-6.108, 106.738] as [number, number],
    area_ha: 25.3,
    health_status: "NORMAL",
    address: "Pantai Indah Kapuk",
    health_reports: [],
  },
  {
    id: "land-6",
    name: "Kebun Pembibitan Marunda",
    position: [-6.098, 106.962] as [number, number],
    area_ha: 5.2,
    health_status: "WARNING",
    address: "Kawasan Pesisir Timur",
    health_reports: [],
  },
  {
    id: "land-7",
    name: "Hutan Lindung Angke Kapuk",
    position: [-6.113, 106.725] as [number, number],
    area_ha: 99.8,
    health_status: "NORMAL",
    address: "Jakarta Barat - Utara",
    health_reports: [],
  },
  {
    id: "land-8",
    name: "Sawah Abadi Cakung",
    position: [-6.182, 106.955] as [number, number],
    area_ha: 12.0,
    health_status: "NORMAL",
    address: "Jakarta Timur",
    health_reports: [],
  },
  {
    id: "land-9",
    name: "Taman Nasional Mangrove B2",
    position: [-6.102, 106.755] as [number, number],
    area_ha: 30.5,
    health_status: "NORMAL",
    address: "Zona Inti Konservasi",
    health_reports: [],
  },
  {
    id: "land-10",
    name: "Lahan Jagung Bekasi Sektor Utara",
    position: [-6.195, 107.025] as [number, number],
    area_ha: 22.1,
    health_status: "WARNING",
    address: "Babelan",
    health_reports: [
      {
        id: "r10",
        confidence_score: 0.88,
        gemini_insight: {
          causes: "Defisiensi Nitrogen",
          recovery: "Bisa Pulih",
          prevention: ["Pemupukan Berimbang"],
          treatment: ["Penambahan pupuk urea"],
          disease_description: "Daun bawah menguning (Mild)",
        },
        is_outbreak_trigger: false,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "land-11",
    name: "Mangrove Restoration Tanjung Pasir",
    position: [-6.015, 106.685] as [number, number],
    area_ha: 55.0,
    health_status: "NORMAL",
    address: "Tangerang Coast",
    health_reports: [],
  },
  {
    id: "land-12",
    name: "Lahan Hortikultura Karawang",
    position: [-6.255, 107.255] as [number, number],
    area_ha: 150.0,
    health_status: "DANGER",
    address: "Telukjambe",
    health_reports: [
      {
        id: "r12",
        confidence_score: 0.96,
        gemini_insight: {
          causes: "Jamur Fusarium",
          recovery: "Sulit",
          prevention: ["Sterilisasi Media Tanam"],
          treatment: ["Pencabutan tanaman terinfeksi agar tidak menular"],
          disease_description: "Layu Fusarium Masif",
        },
        is_outbreak_trigger: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "land-13",
    name: "Hutan Bambu Bekasi",
    position: [-6.252, 106.992] as [number, number],
    area_ha: 3.5,
    health_status: "NORMAL",
    address: "Margahayu",
    health_reports: [],
  },
  {
    id: "land-14",
    name: "Kebun Mangga Indramayu Sektor A",
    position: [-6.325, 108.322] as [number, number],
    area_ha: 80.5,
    health_status: "NORMAL",
    address: "Cikedung",
    health_reports: [],
  },
  {
    id: "land-15",
    name: "Ekowisata Mangrove PIK 2",
    position: [-6.055, 106.695] as [number, number],
    area_ha: 40.0,
    health_status: "WARNING",
    address: "Kawasan Pesisir Baru",
    health_reports: [],
  },
  {
    id: "land-16",
    name: "Lahan Bawang Merah Brebes Utara",
    position: [-6.835, 109.045] as [number, number],
    area_ha: 200.5,
    health_status: "NORMAL",
    address: "Wanasari",
    health_reports: [],
  },
  {
    id: "land-17",
    name: "Hutan Bakau Tangerang",
    position: [-6.025, 106.645] as [number, number],
    area_ha: 18.0,
    health_status: "NORMAL",
    address: "Teluknaga",
    health_reports: [],
  },
  {
    id: "land-18",
    name: "Kebun Teh Puncak Sektor 1",
    position: [-6.702, 106.985] as [number, number],
    area_ha: 350.0,
    health_status: "NORMAL",
    address: "Cisarua",
    health_reports: [],
  },
  {
    id: "land-19",
    name: "Pertanian Hidroponik Urban 1",
    position: [-6.225, 106.845] as [number, number],
    area_ha: 0.5,
    health_status: "NORMAL",
    address: "Tebet",
    health_reports: [],
  },
  {
    id: "land-20",
    name: "Sawah Tadah Hujan Sukabumi",
    position: [-6.925, 106.925] as [number, number],
    area_ha: 85.0,
    health_status: "WARNING",
    address: "Cisaat",
    health_reports: [
      {
        id: "r20",
        confidence_score: 0.85,
        gemini_insight: {
          causes: "Kekeringan",
          recovery: "Tergantung Irigasi",
          prevention: ["Pembuatan Embung"],
          treatment: ["Pompa air darurat"],
          disease_description: "Stunting akibat kurang air",
        },
        is_outbreak_trigger: false,
        created_at: new Date().toISOString(),
      },
    ],
  },
];
